### ISSUE TITLE
spaceで録画エラーが発生し、かつgetmetadataに失敗したときの対処

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/ULTRA#34]
getmetadata()が辞書ではなくint値を返す場合のことを考慮漏れしている

ver.2209.12.469

Traceback (most recent call last):
  File "app.py", line 82, in run
  File "recorder.py", line 178, in run
  File "sources\spaces.py", line 299, in onRecordError
AttributeError: 'int' object has no attribute 'isRunning'

**Comment by yamahubuki** [comment]
space対応昨日削除のため本件クローズします。
